DROP DATABASE IF EXISTS GAMESTATSDB;

CREATE DATABASE GAMESTATSDB;

use GAMESTATSDB;

CREATE TABLE STATS(
    GAME_ID int NOT NULL AUTO_INCREMENT,
    GUESSES int NOT NULL,
    PRIMARY KEY (GAME_ID)
);